'use strict';
const ExcelJS = require('exceljs');

function toNum(val) {
  return parseFloat(String(val || '0').replace(/,/g, '')) || 0;
}

function toTallyDate(dateStr) {
  if (!dateStr || dateStr === 'Unknown') return '';
  const parts = dateStr.split(/[\/\-\. ]/);
  if (parts.length === 3) {
    const d = parts[0].padStart(2, '0');
    const mRaw = parts[1];
    const y = parts[2].length === 2 ? '20' + parts[2] : parts[2];
    const M = { jan:'01',feb:'02',mar:'03',apr:'04',may:'05',jun:'06',
                jul:'07',aug:'08',sep:'09',oct:'10',nov:'11',dec:'12' };
    const m = isNaN(mRaw) ? (M[mRaw.toLowerCase()] || '01') : mRaw.padStart(2, '0');
    return `${y}${m}${d}`;
  }
  return '';
}

async function generateExcel(transactions, companyName, bankLedger, bankType) {
  companyName = companyName || 'My Company';
  bankLedger  = bankLedger  || 'Bank Account';
  bankType    = bankType    || 'Bank';

  const wb = new ExcelJS.Workbook();
  wb.creator = 'Banklyt';
  wb.created  = new Date();

  let totalDebit = 0, totalCredit = 0;
  transactions.forEach(t => {
    const amt = toNum(t.amount);
    (t.type || '').toLowerCase() === 'credit' ? (totalCredit += amt) : (totalDebit += amt);
  });
  const fmt = n => n.toLocaleString('en-IN', { minimumFractionDigits: 2 });

  // ── Sheet 1: Transaction ────────────────────────────────────────────────────
  const ws = wb.addWorksheet('Transaction');
  [14, 58, 26, 14, 20, 20, 20].forEach((w, i) => { ws.getColumn(i + 1).width = w; });

  // Row 1
  ws.mergeCells('A1:C1');
  Object.assign(ws.getCell('A1'), { value: bankType.toUpperCase() + ' Ltd.', font: { bold: true, size: 13 } });
  ws.mergeCells('D1:E1');
  Object.assign(ws.getCell('D1'), { value: 'Page No. : 1', alignment: { horizontal: 'center' }, font: { size: 11 } });
  ws.mergeCells('F1:G1');
  Object.assign(ws.getCell('F1'), { value: 'Statement of accounts', font: { bold: true, size: 11 }, alignment: { horizontal: 'center' } });
  ws.getRow(1).height = 22;
  ws.getRow(2).height = 6;

  // Rows 3-7
  const leftLines  = ['M/S. ' + companyName.toUpperCase(), '', '', '', 'Date: ' + new Date().toLocaleDateString('en-IN')];
  const rightLines = ['Account Branch: ' + bankLedger, 'Ledger: ' + bankLedger, 'Bank: ' + bankType, 'Currency: INR', 'Generated by: Banklyt'];
  leftLines.forEach((txt, i) => {
    const r = 3 + i;
    ws.mergeCells('A' + r + ':C' + r);
    ws.getCell('A' + r).value = txt;
    if (i === 0) ws.getCell('A' + r).font = { bold: true, size: 11 };
    ws.mergeCells('E' + r + ':G' + r);
    ws.getCell('E' + r).value = rightLines[i];
    if (i === 0) ws.getCell('E' + r).font = { bold: true };
    ws.getRow(r).height = 16;
  });
  ws.getRow(8).height = 8;

  // Row 9: totals bar
  ws.mergeCells('A9:C9');
  ws.getCell('A9').value = 'Total Transactions: ' + transactions.length;
  ws.getCell('A9').font  = { bold: true };
  ws.mergeCells('D9:E9');
  Object.assign(ws.getCell('D9'), { value: 'Total Withdrawal: Rs.' + fmt(totalDebit),   font: { bold: true, color: { argb: 'FFE74C3C' } }, alignment: { horizontal: 'center' } });
  ws.mergeCells('F9:G9');
  Object.assign(ws.getCell('F9'), { value: 'Total Deposit: Rs.' + fmt(totalCredit), font: { bold: true, color: { argb: 'FF27AE60' } }, alignment: { horizontal: 'center' } });
  ws.getRow(9).height = 18;
  ws.getRow(10).height = 6;

  // Row 11: column headers
  const HROW = 11;
  const hRow = ws.getRow(HROW);
  hRow.values = ['Date', 'Narration', 'Org./Ref No.', 'Value Dr.', 'Withdrawal Amt.', 'Deposit Amt.', 'Closing Balance'];
  hRow.height = 22;
  hRow.eachCell(cell => {
    cell.font      = { bold: true, size: 10 };
    cell.fill      = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFDDDDDD' } };
    cell.alignment = { vertical: 'middle', horizontal: 'center', wrapText: true };
    cell.border    = { top: { style: 'medium' }, bottom: { style: 'medium' }, left: { style: 'thin' }, right: { style: 'thin' } };
  });

  // Rows 12+: data
  let runningBal = null;
  transactions.forEach((t, i) => {
    const amt      = toNum(t.amount);
    const isCredit = (t.type || '').toLowerCase() === 'credit';
    const parsedBal = t.balance_val != null ? parseFloat(t.balance_val) : null;
    if (parsedBal != null && !isNaN(parsedBal)) {
      runningBal = parsedBal;
    } else if (runningBal != null) {
      runningBal = isCredit ? runningBal + amt : runningBal - amt;
    }

    const row = ws.getRow(HROW + 1 + i);
    row.values  = [t.date || '', t.description || '', t.refNo || '', t.date || '', isCredit ? '' : amt, isCredit ? amt : '', runningBal != null ? runningBal : ''];
    row.height  = 16;

    if (isCredit) {
      row.eachCell(cell => { cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFFF99' } }; });
    }

    row.getCell(5).font = { color: { argb: 'FFE74C3C' } };
    row.getCell(6).font = { color: { argb: 'FF27AE60' } };
    [5, 6, 7].forEach(col => { if (row.getCell(col).value !== '') row.getCell(col).numFmt = '#,##0.00'; });
    row.eachCell(cell => {
      cell.border = { bottom: { style: 'thin', color: { argb: 'FFCCCCCC' } }, left: { style: 'thin', color: { argb: 'FFCCCCCC' } }, right: { style: 'thin', color: { argb: 'FFCCCCCC' } } };
    });
  });

  ws.views = [{ state: 'frozen', ySplit: HROW }];

  // ── Sheet 2: Summary ────────────────────────────────────────────────────────
  const ws2 = wb.addWorksheet('Summary');
  ws2.getColumn(1).width = 32;
  ws2.getColumn(2).width = 22;
  ws2.mergeCells('A1:B1');
  ws2.getCell('A1').value = 'Banklyt — Export Summary';
  ws2.getCell('A1').font  = { bold: true, size: 14 };
  ws2.getRow(1).height    = 26;

  const sRows = [
    ['Company Name', companyName],
    ['Bank / Ledger', bankType + ' — ' + bankLedger],
    ['Total Transactions', transactions.length],
    ['Total Withdrawals', totalDebit],
    ['Total Deposits',    totalCredit],
    ['Net Balance',       totalCredit - totalDebit],
    ['Generated On',      new Date().toLocaleDateString('en-IN')],
  ];
  sRows.forEach((data, i) => {
    const r = ws2.getRow(3 + i);
    r.values = data;
    r.getCell(1).font = { bold: true };
    r.height = 18;
    if (i >= 3 && i <= 5) r.getCell(2).numFmt = '#,##0.00';
  });
  ws2.getRow(6).getCell(2).font = { bold: true, color: { argb: 'FFE74C3C' } };
  ws2.getRow(7).getCell(2).font = { bold: true, color: { argb: 'FF27AE60' } };

  return await wb.xlsx.writeBuffer();
}

function generateTallyXML(transactions, companyName, bankLedger) {
  companyName = companyName || 'My Company';
  bankLedger  = bankLedger  || 'Bank Account';
  const esc = s => String(s || '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');

  const vouchers = transactions.map(t => {
    const amt      = toNum(t.amount);
    const isCredit = (t.type || '').toLowerCase() === 'credit';
    const vchType  = isCredit ? 'Receipt' : 'Payment';
    const party    = esc(t.category && t.category !== 'Misc' ? t.category : (t.description || 'Miscellaneous').substring(0, 40));
    const amtStr   = amt.toFixed(2);
    return '    <TALLYMESSAGE xmlns:UDF="TallyUDF">\n      <VOUCHER VCHTYPE="' + vchType + '" ACTION="Create" OBJVIEW="Accounting Voucher View">\n        <DATE>' + toTallyDate(t.date) + '</DATE>\n        <EFFECTIVEDATE>' + toTallyDate(t.date) + '</EFFECTIVEDATE>\n        <VOUCHERTYPENAME>' + vchType + '</VOUCHERTYPENAME>\n        <NARRATION>' + esc(t.description || '') + '</NARRATION>\n        <ALLLEDGERENTRIES.LIST>\n          <LEDGERNAME>' + esc(bankLedger) + '</LEDGERNAME>\n          <ISDEEMEDPOSITIVE>' + (isCredit ? 'Yes' : 'No') + '</ISDEEMEDPOSITIVE>\n          <AMOUNT>' + (isCredit ? '-' : '') + amtStr + '</AMOUNT>\n        </ALLLEDGERENTRIES.LIST>\n        <ALLLEDGERENTRIES.LIST>\n          <LEDGERNAME>' + party + '</LEDGERNAME>\n          <ISDEEMEDPOSITIVE>' + (isCredit ? 'No' : 'Yes') + '</ISDEEMEDPOSITIVE>\n          <AMOUNT>' + (isCredit ? '' : '-') + amtStr + '</AMOUNT>\n        </ALLLEDGERENTRIES.LIST>\n      </VOUCHER>\n    </TALLYMESSAGE>';
  }).join('\n');

  return '<?xml version="1.0" encoding="UTF-8"?>\n<ENVELOPE>\n  <HEADER><TALLYREQUEST>Import Data</TALLYREQUEST></HEADER>\n  <BODY>\n    <IMPORTDATA>\n      <REQUESTDESC>\n        <REPORTNAME>Vouchers</REPORTNAME>\n        <STATICVARIABLES><SVCURRENTCOMPANY>' + esc(companyName) + '</SVCURRENTCOMPANY></STATICVARIABLES>\n      </REQUESTDESC>\n      <REQUESTDATA>\n' + vouchers + '\n      </REQUESTDATA>\n    </IMPORTDATA>\n  </BODY>\n</ENVELOPE>';
}

module.exports = { generateExcel, generateTallyXML };
